%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Core Model, 2022
% Written by Maya Davis
% Concept by Maya Davis and Melissa A. Redford
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% TESTS

function TestResults = AllSimpleTests
    Tests = ["TestClusterSimple" "TestDistancePointToSimplexSimple", ...
        "TestExecutionParametersSimple", "TestGoalSimple", ...
        "TestJunctureSimple", "TestMakeManyHyperCubeClustersSimple", ...
        "TestMotorPointSimple", "TestMotorSilhouetteSimple", ...
        "TestMotorTrajectorySimple", "TestPerceptualPointSimple", ...
        "TestPerceptualTrajectorySimple", "TestSpaceSimple", ...
        "TestSpaceTransformationSimple", ...
        "TestWeightedMotorSimplicialComplexSimple"];
    TestResults = runtests(Tests(1));
    for i = 2:numel(Tests)
        TestResults = [TestResults runtests(Tests(i))];
    end
end
