%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Core Model, 2022
% Written by Maya Davis
% Concept by Maya Davis and Melissa A. Redford
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function fullFigureData = FindFullFigureData(goal, plottingParameters, axesList, ...
    axesWithMotorClusters, axesWithPerceptualClusters, ...
    motorClustersActivations, perceptualClustersActivations, ...
    axesWithSilhouette, silhouetteActivations, axesWithTrajectory, ...
    axesWithMotorResult, motorResult, axesWithPerceptualResult, ...
    perceptualResult)
    [MCXValues, MCYValues, MCColorValues, MCAlphaValues] = ...
                goal.Space.MotorClusterPlottingInfo(...
                plottingParameters.ClusterColorArray, AlphaClusterValues);
    [PCXValues, PCYValues, PCColorValues, PCAlphaValues] = ...
                    goal.Space.PerceptualClusterPlottingInfo(...
                    plottingParameters.ClusterColorArray, AlphaClusterValues);
    
    clusterXList = {MCXValues; MCXValues; MCXValues; MCXValues; ...
        PCXValues; PCXValues; PCXValues; PCXValues};
    clusterYList = {MCYValues; MCYValues; MCYValues; MCYValues; ...
        PCYValues; PCYValues; PCYValues; PCYValues};
    clusterColorList = {MCColorValues; MCColorValues; MCColorValues; ...
        MCColorValues; PCColorValues; PCColorValues; ...
        PCColorValues; PCColorValues};
    clusterAlphaList = {MCAlphaValues; MCAlphaValues; MCAlphaValues; ...
        MCAlphaValues; PCAlphaValues; PCAlphaValues; PCAlphaValues; PCAlphaValues};
    % clusterAlphaList = {transpose(0:0.05:0.75); transpose(0:0.02:0.3); ...
    %     transpose(0.6:0.02:0.9); transpose(0.25:0.05:1); ...
    %     transpose(0:0.05:0.75); transpose(0:0.02:0.3); ...
    %     transpose(0.6:0.02:0.9); transpose(0.25:0.05:1)};
    
    % Silhouette values
    [VertexData, FaceData] = ExampleGoal.Silhouette.PlottingInfo(...
        ExPlotParams.NumberOfSilhouetteVertices);
    silhouetteFaceList = {FaceData; FaceData; FaceData; FaceData; ...
        []; []; []; []};
    silhouetteVertexList = {VertexData; VertexData; VertexData; VertexData; ...
        []; []; []; []};
    silhoutteColorArray = [ExPlotParams.MotorSilhouetteColor1; ...
        ExPlotParams.MotorSilhouetteColor1; ...
        ExPlotParams.MotorSilhouetteColor1; ...
        ExPlotParams.MotorSilhouetteColor1];
    silhouetteColorList = {silhoutteColorArray; silhoutteColorArray; ...
        silhoutteColorArray; silhoutteColorArray; silhoutteColorArray; ...
        silhoutteColorArray; silhoutteColorArray; silhoutteColorArray};
    silhouetteAlphaArray = [1; 1; 1; 1];
    silhouetteAlphaList = {silhouetteAlphaArray; silhouetteAlphaArray; ...
        silhouetteAlphaArray; silhouetteAlphaArray; silhouetteAlphaArray; ...
        silhouetteAlphaArray; silhouetteAlphaArray; silhouetteAlphaArray};
    
    % Trajectory values
    [trajectoryXValues, trajectoryYValues, trajectoryColorValues] = ...
        ExampleGoal.Trajectory.PlottingInfo(...
        ExPlotParams.PerceptualTrajectoryColor1, ...
        ExPlotParams.PerceptualTrajectoryColor2);
    trajectoryXList = {[]; []; []; []; trajectoryXValues; ...
        trajectoryXValues; trajectoryXValues; trajectoryXValues};
    trajectoryYList = {[]; []; []; []; trajectoryYValues; ...
        trajectoryYValues; trajectoryYValues; trajectoryYValues};
    trajectoryColorList = {[]; []; []; []; trajectoryColorValues; ...
        trajectoryColorValues; trajectoryColorValues; trajectoryColorValues};
    
    % Result values
    ExampleResultMP1 = MotorPoint([24; 22]);
    ExampleResultMP2 = MotorPoint([30; 28]);
    ExampleResultMP3 = MotorPoint([20; 16]);
    ExampleResultMP4 = MotorPoint([20; 8]);
    ExampleResultJuncture1 = ExampleResultMP1.MakeJuncture(ExampleSpace.SpaceTransformation);
    ExampleResultJuncture2 = ExampleResultMP2.MakeJuncture(ExampleSpace.SpaceTransformation);
    ExampleResultJuncture3 = ExampleResultMP3.MakeJuncture(ExampleSpace.SpaceTransformation);
    ExampleResultJuncture4 = ExampleResultMP4.MakeJuncture(ExampleSpace.SpaceTransformation);
    % Make general motor trajectory and perceptual trajectory that values will come from
    ResultMotorPath = {ExampleResultJuncture1.MotorPoint; ...
        ExampleResultJuncture2.MotorPoint; ...
        ExampleResultJuncture3.MotorPoint; ExampleResultJuncture4.MotorPoint};
    ResultPerceptualPath = {ExampleResultJuncture1.PerceptualPoint; ...
        ExampleResultJuncture2.PerceptualPoint; ...
        ExampleResultJuncture3.PerceptualPoint; ...
        ExampleResultJuncture4.PerceptualPoint};
    % Initialize sizes
    FullTimeArray = {1; 2; 3; 4};
    resultMotorXList = cell(4,1);
    resultMotorYList = cell(4,1);
    resultMotorColorList = cell(4,1);
    resultPerceptualXList = cell(4,1);
    resultPerceptualYList = cell(4,1);
    resultPerceptualColorList = cell(4,1);
    
    for t = 1:4
        CurrentMotorTrajectory = MotorTrajectory(FullTimeArray(1:t,1), ResultMotorPath(1:t,1));
        [MXValues, MYValues, MColorValues] = ...
            CurrentMotorTrajectory.PlottingInfo(...
            ExPlotParams.ResultTrajectoryColor1, ...
            ExPlotParams.ResultTrajectoryColor2, ...
            ExPlotParams.ResultPointSizes, 5);
        CurrentPerceptualTrajectory = PerceptualTrajectory(FullTimeArray(1:t,1), ResultPerceptualPath(1:t,1), 5*ones(t-1,1));
        [PXValues, PYValues, PColorValues] = ...
            CurrentPerceptualTrajectory.PlottingInfo(...
            ExPlotParams.ResultTrajectoryColor1, ...
            ExPlotParams.ResultTrajectoryColor2);
        resultMotorXList{t,1} = MXValues;
        resultMotorYList{t,1} = MYValues;
        resultMotorColorList{t,1} = MColorValues;
        resultPerceptualXList{t,1} = PXValues;
        resultPerceptualYList{t,1} = PYValues;
        resultPerceptualColorList{t,1} = PColorValues;
    end
    
    
    resultXList = [resultMotorXList; resultPerceptualXList];
    resultYList = [resultMotorYList; resultPerceptualYList];
    
    resultColorList = [resultMotorColorList; resultPerceptualColorList];
    junctureSizes = ExPlotParams.JunctureSizes;
    resultPointSizes = ExPlotParams.ResultPointSizes;
    fullFigureData = FullFigureData(axesList, clusterXList, ...
        clusterYList, clusterColorList, clusterAlphaList, ...
        silhouetteFaceList, silhouetteVertexList, ...
        silhouetteColorList, silhouetteAlphaList, ...
        trajectoryXList, trajectoryYList, trajectoryColorList, ...
        resultXList, resultYList, resultColorList, ...
        junctureSizes, resultPointSizes);
end